baseurl = "/"
RelativeURLs=true
CanonifyURLs=true
languageCode = "en-us"
title = "Chun-Jie Liu | 柳纯洁"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true  # .WordCount works correctly for chinese
enableEmoji = true
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
MetaDataFormat = "yaml" # format of a new post
enableGitInfo = false

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "English"
    url = "/en/"
    weight = 1

[[menu.en]]
    name = "Home"
    url = '/'
    weight = 1

[[menu.en]]
    name = "About"
    url = '/en/about/'
    weight = 2

[[menu.main]]
    name = "中文"
    url = '/cn/'
    weight = 2

[[menu.cn]]
    name = "首页"
    url = '/'
    weight = 1

[[menu.cn]]
    name = "关于"
    url = '/cn/about/'
    weight = 2

[params]
    description = "Window to Chun-Jie Liu"
    disqusURL = "https://chunjie-sam-liu.life"
    customJS = ["js/fix-toc.js", "js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js", "js/external-link.js", "js/alt-title.js", "js/header-link.js"]
    githubContentURL = "https://github.com/chunjie-sam-liu/chunjie-sam-liu.life/edit/master/content/"

    highlightjsVersion = "9.12.0"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsTheme = "github"
    dateFormat = "2006-01-02"

[params.footer]
    home = "Powered by [Hugo](https://gohugo.io) and [Blogdown](https://bookdown.org/yihui/blogdown/) &copy; [Chun-Jie Liu](/) 2019 - "
    en = "&copy; [Chun-Jie Liu](https://chunjie-sam-liu.life) 2019 | [Github](https://github.com/chunjie-sam-liu) | [Twitter](https://twitter.com/chunjiesamliu)"
    cn = "&copy; [Chun-Jie Liu](https://chunjie-sam-liu.life) 2019 | [Github](https://github.com/chunjie-sam-liu) | [Twitter](https://twitter.com/chunjiesamliu)"

[params.author]
    en = "Chun-Jie Liu"
    cn = "柳纯洁"

[params.logo.en]
    img = "https://chunjie-sam-liu.life/img/donate.jpeg"
    url = "/"
    alt = "Chun-Jie Liu"
    tag = ""
